name: Apply Database Migration
description: Add and remove IP address from an Azure SQL server and apply a database migration to it.

inputs:
  db_context:
    required: true
    type: string
  data_project_path:
    required: true
    type: string
  startup_project_path:
    required: true
    type: string
  azure_resource_group:
    required: true
    type: string
  azure_sql_server_resource_name:
    required: true
    type: string
  az_firewall_rule_name:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Get Workflow Runner IP
      id: runner-ip
      uses: ./.github/actions/get-runner-ip-address

    - name: Add Azure Firewall Rule
      uses: ./.github/actions/azure-firewall-ip
      with:
        ip_address: ${{ steps.runner-ip.outputs.ip_address }}
        action: "Add"
        az_resource_group: ${{ inputs.azure_resource_group }}
        az_sql_server_name: ${{ inputs.azure_sql_server_resource_name }}
        az_firewall_rule_name: ${{ inputs.az_firewall_rule_name }}

    - name: Apply Database Migration
      shell: bash
      run: dotnet ef database update -c ${{ inputs.db_context }} --project ${{ inputs.data_project_path }} --startup-project ${{ inputs.startup_project_path }}

    - name: Remove Azure Firewall Rule
      if: always()
      uses: ./.github/actions/azure-firewall-ip
      with:
        ip_address: ${{ steps.runner-ip.outputs.ip_address }}
        action: "Remove"
        az_resource_group: ${{ inputs.azure_resource_group }}
        az_sql_server_name: ${{ inputs.azure_sql_server_resource_name }}
        az_firewall_rule_name: ${{ inputs.az_firewall_rule_name }}