name: Run E2E Seed Script
description: Run either the Setup or Teardown script from the E2E seeding mini-project

inputs:
  resource_group:
    required: true
    description: Name of the resource group linked to the SQL Server
  sql_server:
    required: true
    description: Name of the SQL Server to run the seed script(s) against
  connection_string_service_directory:
    required: true
    description: The connection string to the Service Directory Db
  connection_string_referral:
    required: true
    description: The connection string to the Referral Db
  connection_string_report:
    required: true
    description: The connection string to the Report Db
  encryption_key:
    required: true
    description: The column encryption key for the Referral Db
  initialisation_vector:
    required: true
    description: The column initialisation vector for the Referral Db
  action:
    required: true
    type: choice
    options:
      - "Setup"
      - "Teardown"
  
runs:
  using: composite

  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: "lts/Jod" # Jod is the codename for 22 LTS

    - name: Install NPM Packages
      shell: bash
      run: npm i

    - name: Create Environment Variables
      shell: bash
      run: |
        cat <<EOF>> .env
        IDS_START_FROM=1000000
        CONNECTION_STRING_SERVICEDIRECTORY='${{ inputs.connection_string_service_directory }}'
        CONNECTION_STRING_REFERRAL='${{ inputs.connection_string_referral }}'
        CONNECTION_STRING_REPORT='${{ inputs.connection_string_report }}'
        ENCRYPTION_KEY='${{ inputs.encryption_key }}'
        INITIALISATION_VECTOR='${{ inputs.initialisation_vector }}'
        EXAMPLE_SEED='False'
        EOF

    - name: Get Workflow Runner IP
      id: runner-ip
      uses: ./.github/actions/get-runner-ip-address

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Add Azure Firewall Rule
      uses: ./.github/actions/azure-firewall-ip
      with:
        ip_address: ${{ steps.runner-ip.outputs.ip_address }}
        action: "Add"
        az_resource_group: ${{ inputs.RESOURCE_GROUP }}
        az_sql_server_name: ${{ inputs.SQL_SERVER }}
        az_firewall_rule_name: e2e-seed-script

    - name: Run Setup
      if: ${{ inputs.action == 'Setup' }}
      shell: bash
      run: npm run setup:dev

    - name: Run Teardown
      if: ${{ inputs.action == 'Teardown' }}
      shell: bash
      run: npm run teardown:dev

    - name: Remove Azure Firewall Rule
      if: always()
      uses: ./.github/actions/azure-firewall-ip
      with:
        ip_address: ${{ steps.runner-ip.outputs.ip_address }}
        action: "Remove"
        az_resource_group: ${{ inputs.RESOURCE_GROUP }}
        az_sql_server_name: ${{ inputs.SQL_SERVER }}
        az_firewall_rule_name: e2e-seed-script