name: Build & Test

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    paths:
      - '.github/workflows/build-and-test.yml'
      - 'src/**'

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          [
            service/notification-api,
            service/idam-api,
            service/service-directory-api,
            service/referral-api,
            service/report-api,
            ui/connect-dashboard-ui,
            ui/connect-ui,
            ui/find-ui,
            ui/idam-maintenance-ui,
            ui/manage-ui,
            shared/referral-shared,
            shared/service-directory-shared,
            shared/shared-kernel,
            shared/web-components
          ]
        include:
          - working_directory: service/service-directory-api
            run_install_spatialite: true
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      working_directory: ${{ matrix.working_directory }}
      dotnet_version: ${{ vars.DOTNET_VERSION }}
      run_install_spatialite: ${{ matrix.run_install_spatialite && true || false }}
