name: Build & Test .NET Projects

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
    paths:
      - '.github/workflows/build-and-test-matrix.yml'
      - '.github/workflows/build-and-test-project.yml'
      - 'src/**'

jobs:
  build-and-test-projects-linux:
    name: ${{ matrix.working_directory }}
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          [
            src/service/notification-api,
            src/service/idam-api,
            src/service/service-directory-api
            src/service/referral-api,
            src/service/report-api,
            src/ui/connect-dashboard-ui,
            src/ui/connect-ui,
            src/ui/find-ui,
            src/ui/idam-maintenance-ui,
            src/ui/manage-ui,
            src/shared/referral-shared,
            src/shared/service-directory-shared,
            src/shared/shared-kernel,
            src/shared/web-components,
          ]
    uses: ./.github/workflows/build-and-test-project.yml
    with:
      working_directory: ${{ matrix.working_directory }}
      runner: ubuntu-22.04
