name: Build & Test .NET Project

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  build-test-project:
    name: Build & Test
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Install Dependencies
        if: ${{ inputs.runner == 'ubuntu-22.04' }}
        shell: bash
        run: > 
          sudo apt install libsqlite3-mod-spatialite

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ vars.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Project
        shell: bash
        run: dotnet restore

      - name: Build Project
        shell: bash
        run: dotnet build --no-restore

      - name: Test Project
        shell: bash
        run: dotnet test --no-build --no-restore --verbosity minimal
