# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & test .NET

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: ["main", "release*"]
  pull_request:

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build-notification-api:
    name: Build & test service/notification-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/notification-api/

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-idam-api:
    name: Build & test service/idam-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/idam-api/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-referral-api:
    name: Build & test service/referral-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/referral-api/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-report-api:
    name: Build & test service/report-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/report-api/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-service-directory-api:
    name: Build & test service/service-directory-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/service-directory-api/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: >
          sudo apt-get install libsqlite3-mod-spatialite
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-connect-dashboard-ui:
    name: Build & test ui/connect-dashboard-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui/connect-dashboard-ui/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-connect-ui:
    name: Build & test ui/connect-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui/connect-ui/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-find-ui:
    name: Build & test ui/find-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui/find-ui/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-idam-maintenance-ui:
    name: Build & test ui/idam-maintenance-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui/idam-maintenance-ui/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-manage-ui:
    name: Build & test ui/manage-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/ui/manage-ui/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-referal-shared:
    name: Build & test shared/referral-shared
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/shared/referral-shared/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-service-directory-shared:
    name: Build & test shared/service-directory-shared
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/shared/service-directory-shared/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-shared-kernel:
    name: Build & test shared/shared-kernel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/shared/shared-kernel/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal

  build-web-components:
    name: Build & test shared/web-components
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/shared/web-components/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal
