name: Deploy
run-name: Deploy to ${{ inputs.environment }}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for deployment
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Test'
          - 'Production'

permissions:
  id-token: write
  contents: read

jobs:
  build-projects-upload-artifacts:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        project: [ src/service/idam-api/,
#                   src/service/notification-api/,
#                   src/service/referral-api/,
#                   src/service/report-api/,
#                   src/service/service-directory-api/,
#                   src/ui/connect-dashboard-ui/,
#                   src/ui/connect-ui/,
#                   src/ui/find-ui/,
#                   src/ui/idam-maintenance-ui/,
#                   src/ui/manage-ui/
                   ]
    uses: ./.github/workflows/build-upload-artefact.yml
    with:
      project: ${{ matrix.project }}
    secrets: inherit

  idam-deploy:
    needs: [ build-projects-upload-artifacts ]
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ inputs.environment }}
      service_name: IDAM API
      artifact_name: idam-api
      keyvault_prefix: IDAM-API
      project_name: FamilyHubs.Idam.Api
      data_project_name: FamilyHubs.Idam.Data
      project_type: service
      azure_app_name: s181d01-as-fh-idam-api
