name: Deploy to dev

concurrency: deploy-dev

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME_IDAM_API: s181d01-as-fh-idam-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish-idam-api:
    name: Build, test & publish service/idam-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/idam-api/
    env:
      STARTUP_PROJECT_PATH: src/FamilyHubs.Idam.Api

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish ${{ format('{0}/*.csproj', env.STARTUP_PROJECT_PATH) }} -c Release -o release

      - name: Upload artifact for deployment jobyml
        uses: actions/upload-artifact@v3
        with:
          name: .net-idam-api
          path: './release'

  deploy-idam-api:
    name: Deploy service/idam-api
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment: development
    needs: [build-and-publish-idam-api]
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-idam-api

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          APPINSIGHTS_CONNECTION_STRING: ${{ secrets.IDAM_API_APPINSIGHTS_CONNECTION_STRING }}
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ vars.IDAM_API_APPINSIGHTS_INSTRUMENTATIONKEY }}
          ConnectionStrings.IdamConnection: ${{ secrets.IDAM_API_CONNECTIONSTRINGS_IDAMCONNECTION }}
          Crypto.clientId: ${{ vars.IDAM_API_CRYPTO_CLIENTID }}
          Crypto.clientSecret: ${{ secrets.IDAM_API_CRYPTO_CLIENTSECRET }}
          Crypto.DbEncryptionIVKey: ${{ secrets.IDAM_API_CRYPTO_DBENCRYPTIONIVKEY }}
          Crypto.DbEncryptionIVKeySecretName: ${{ vars.IDAM_API_CRYPTO_DBENCRYPTIONIVKEYSECRETNAME }}
          Crypto.DbEncryptionKey: ${{ secrets.IDAM_API_CRYPTO_DBENCRYPTIONKEY }}
          Crypto.DbEncryptionKeySecretName: ${{ vars.IDAM_API_CRYPTO_DBENCRYPTIONKEYSECRETNAME }}
          Crypto.KeyVaultIdentifier: ${{ vars.IDAM_API_CRYPTO_KEYVAULTIDENTIFIER }}
          Crypto.tenantId: ${{ vars.IDAM_API_CRYPTO_TENANTID }}
          Crypto.UseKeyVault: ${{ vars.IDAM_API_CRYPTO_USEKEYVAULT }}
          EventGridUrl: ${{ vars.IDAM_API_EVENTGRIDURL }}
          GovUkOidcConfiguration.BearerTokenSigningKey: ${{ secrets.IDAM_API_GOVUKOIDCCONFIGURATION_BEARERTOKENSIGNINGKEY }}
          ServiceDirectoryApiBaseUrl: ${{ vars.IDAM_API_SERVICEDIRECTORYAPIBASEURL }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_IDAM_API }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_IDAM_API }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}