name: Deploy
run-name: Deploy to ${{ inputs.environment }}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for deployment
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Test'

permissions:
  id-token: write
  contents: read

jobs:
  build-projects-upload-artifacts:
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: true
      matrix:
        project: [ src/service/report-api/,
                 ]
        include:
          - project: src/service/report-api/
            job_name: Build - Report API
    uses: ./.github/workflows/build-upload-artifact.yml
    with:
      project: ${{ matrix.project }}

  run-api-acceptance-tests:
    if: inputs.environment == 'Test' || inputs.environment == 'Test2'
    name: ${{ matrix.job_name }}
    needs: [ build-projects-upload-artifacts ]
    strategy:
      matrix:
        project_name: [
          report-api,
          referral-api
        ]
        include:
          - project_name: report-api
            job_name: Test - Report API
            keyvault_prefix: TEST-REPORT-API
            test_project_name: FamilyHubs.Report.Api.AcceptanceTests
          - project_name: referral-api
            job_name: Test - Referral API
            keyvault_prefix: TEST-Referral-API
            test_project_name: FamilyHubs.Referral.Api.AcceptanceTests  
    uses: ./.github/workflows/run-acceptance-tests.yml
    with:
      environment: ${{ inputs.environment }}
      project_name: ${{ matrix.project_name }}
      keyvault_prefix: ${{ matrix.keyvault_prefix }}
      test_project_name: ${{ matrix.test_project_name }}
      project_type: service
    secrets: inherit