name: Deploy
run-name: Deploy to ${{ inputs.environment }}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for deployment
        default: 'Development'
        type: choice
        options:
          - 'Development'

permissions:
  id-token: write
  contents: read

jobs:
  build-projects-upload-artifacts:
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: true
      matrix:
        project: [ src/service/service-directory-api/
        ]
        include:
          - project: src/service/service-directory-api/
            publish_project: FamilyHubs.ServiceDirectory.Api
            job_name: Build - Service Directory API
    uses: ./.github/workflows/build-upload-artifact.yml
    with:
      project: ${{ matrix.project }}
      publish_project: ${{ matrix.publish_project }}
      dotnet_version: ${{ matrix.dotnet_version_override || vars.DOTNET_VERSION }}

  deploy-api-services:
    name: ${{ matrix.job_name }}
    needs: [ build-projects-upload-artifacts ]
    strategy:
      matrix:
        artifact_name: [ 
                         service-directory-api
        ]
        include:
          - artifact_name: service-directory-api
            job_name: Deploy - Service Directory API
            keyvault_prefix: SD-API
            project_name: FamilyHubs.ServiceDirectory.Api
            data_project_name: FamilyHubs.ServiceDirectory.Data
            database_context: ApplicationDbContext
            azure_app_name: as-fh-sd-api
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ inputs.environment }}
      artifact_name: ${{ matrix.artifact_name }}
      keyvault_prefix: ${{ matrix.keyvault_prefix }}
      project_name: ${{ matrix.project_name }}
      data_project_name: ${{ matrix.data_project_name }}
      database_context: ${{ matrix.database_context }}
      project_type: service
      azure_app_name: ${{ matrix.azure_app_name }}
    secrets: inherit