# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-notification-api:
    name: Build & test notification-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/service/notification-api/

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test idam-api
        run: dotnet test --no-build --verbosity normal
        working-directory: src/service/idam-api/
