name: Matrix Build & Test All .NET Projects

on:
    push:
      branches:
        - '*'         # matches every branch that doesn't contain a '/'
        - '*/*'       # matches every branch containing a single '/'
        - '**'        # matches every branch
        - '!main'     # excludes main
    pull_request:
      branches:
        - '*'

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  set-env:
    runs-on: ubuntu-22.04
    name: Set Environment
    outputs:
      dotnet_version: ${{ steps.var.outputs.dotnet_version }}
    steps:
      - id: var
        run: |
          DOTNET_VERSION=${{ env.DOTNET_VERSION }}
          echo "dotnet_version=${DOTNET_VERSION}" >> $GITHUB_OUTPUT

  build-and-test-projects:
    name: Build & Test
    needs: [ set-env ]
    strategy:
      fail-fast: false
      matrix:
        working_directory: [ src/service/notification-api/,
                             src/service/idam-api/,
                             src/service/referral-api/,
                             src/service/report-api/,
                             src/service/service-directory-api/,
                             src/ui/connect-dashboard-ui/,
                             src/ui/connect-ui/,
                             src/ui/find-ui/,
                             src/ui/idam-maintenance-ui/,
                             src/ui/manage-ui/,
                             src/shared/referral-shared/,
                             src/shared/service-directory-shared/,
                             src/shared/shared-kernel/,
                             src/shared/web-components/ ]
        dotnet_version: [ "${{env.DOTNET_VERSION }}" ]
    uses: ./.github/workflows/build-and-test-project.yml
    with:
      working_directory: ${{ matrix.working_directory }}
      dotnet_version: ${{ needs.set-env.outputs.dotnet_version }}
