name: Run Playwright E2E Tests

on:
  workflow_call:
    inputs:
      environment:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for running E2E tests
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Test'
          - 'Test2'
          - 'Pre-production'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  SEED_SCRIPT_WORKING_DIRECTORY: "test/e2e-seed-data-framework"

jobs:
  pre-test-teardown:
    if: ${{ inputs.environment != 'Production' }}
    name: Pre-Test Database Teardown
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.SEED_SCRIPT_WORKING_DIRECTORY }}
          action: "Teardown"
  
  pre-test-setup:
    needs: [ pre-test-teardown ]
    name: Pre-Test Database Setup
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Setup Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.SEED_SCRIPT_WORKING_DIRECTORY }}
          action: "Setup"
  
  run-test-suites:
    needs: [ pre-test-setup ]
    name: Run ${{ matrix.job_name }}
    strategy:
      fail-fast: false
      matrix:
        suite: [ find-e2e-tests, manage-e2e-tests ]
        include:
          - suite: find-e2e-tests
            job_name: "Find E2E Test Suite"
          - suite: manage-e2e-tests
            job_name: "Manage E2E Test Suite"
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Test Suite
        shell: bash
        run: exit 1 # Exit 0 simulates success, Exit 1 simulates fail
  
  post-test-teardown:
    needs: [ run-test-suites ]
    name: Post-Test Database Teardown
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.SEED_SCRIPT_WORKING_DIRECTORY }}
          action: "Teardown"