name: Run SQL Script
run-name: ${{ inputs.title }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Environment to apply database teardown script to
      title:
        required: true
        type: string
        description: Title for the workflow  
      keyvault_secret_name:
        required: true
        type: string
        description: Name of the secret containing the database connection string
      sql_file_path:
        required: true
        type: string
        description: Path to the SQL file

jobs:
  run-script-against-database:
    name: Runs theSQL script against the selected database
    runs-on: windows-2022
    environment: ${{ inputs.environment }}
    env:
      KEYVAULT_NAME: ${{ vars.AZURE_RESOURCE_PREFIX }}-kv-fh-general
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run SQL Script PowerShell
        uses: ./.github/actions/run-sql-script
        with:
          keyvault_secret_name: ${{ inputs.keyvault_secret_name }}
          sql_file_path: ${{ inputs.sql_file_path }}