name: Run E2E Test Seed Scripts

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for running the seed scripts
        default: "Development"
        type: choice
        options:
          - "Development"
          - "Test"
          - "Test2"
      action:
        description: Script(s) to run
        default: "Setup & Teardown"
        type: choice
        options:
          - "Setup"
          - "Teardown"
          - "Setup & Teardown"

permissions:
  id-token: write
  contents: read

env:
  WORKING_DIRECTORY: "test/e2e-seed-data-framework"

jobs:
  run-pre-setup-teardown:
    if: ${{ startsWith(inputs.action, 'Setup') }}
    name: Run Pre-Setup Teardown Script
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
          action: "Teardown"

  run-setup:
    needs: [run-pre-setup-teardown]
    if: ${{ startsWith(inputs.action, 'Setup') }}
    name: Run Setup Script
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Setup Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
          action: "Setup"

  run-teardown:
    needs: [run-setup]
    if: ${{ always() && (endsWith(inputs.action, 'Teardown') && ( needs.run-setup.result == 'success' || needs.run-setup.result == 'skipped' ))}}
    name: Run Teardown Script
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown Script
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          connection_string_service_directory: ${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}
          connection_string_referral: ${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}
          connection_string_report: ${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}
          encryption_key: ${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}
          initialisation_vector: ${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          working_directory: ${{ env.WORKING_DIRECTORY }}
          action: "Teardown"
