name: Run E2E Test Seed Scripts

# TODO: Move this into a reusable action to be called elsewhere rather than a workflow.. But for now this is good for testing

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch: # TODO: Temporary for testing
    inputs:
      environment:
        description: The environment target for running the seed scripts
        default: "Development"
        type: choice
        options:
          - "Development"
          - "Test"
          - "Test2"
      action:
        description: Script(s) to run
        default: "Setup & Teardown"
        type: choice
        options:
          - "Setup"
          - "Teardown"
          - "Setup & Teardown"

permissions:
  id-token: write
  contents: read

jobs:
  run-pre-setup-teardown:
    if: ${{ startsWith(inputs.action, 'Setup') }}
    name: Run Pre-Setup Teardown
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          action: "Teardown"

  run-setup:
    needs: [run-pre-setup-teardown]
    if: ${{ startsWith(inputs.action, 'Setup') }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Setup
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          action: "Setup"

  run-teardown:
    needs: [run-setup]
    if: ${{ always() && (endsWith(inputs.action, 'Teardown') && ( needs.run-setup.result == 'success' || needs.run-setup.result == 'skipped' ))}}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Teardown
        uses: ./.github/actions/run-e2e-seed-script
        with:
          resource_group: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
          sql_server: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
          action: "Teardown"
