name: Run E2E Test Seed Scripts (Temporary)

# TODO: Move this into a reusable action to be called elsewhere rather than a workflow.. But for now this is good for testing

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch: # TODO: Temporary for testing
    inputs:
      environment:
        description: The environment target for running the seed scripts
        default: "Development"
        type: choice
        options:
          - "Development"
          - "Test"
          - "Test2"
      setup: # TODO: Temporary for testing
        description: Run the setup script
        default: "True"
        type: choice
        options:
          - "True"
          - "False"
      teardown: # TODO: Temporary for testing
        description: Run the teardown script
        default: "True"
        type: choice
        options:
          - "True"
          - "False"

permissions:
  id-token: write
  contents: read

jobs:
  run-setup-script:
    if: ${{ inputs.setup == 'True' }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: "test/e2e-seed-data-framework"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Jod"

      - name: Install NPM Packages
        shell: bash
        run: npm i

      - name: Initialise Environment Variables
        shell: bash
        run: |
          cat <<EOF>> .env
          IDS_START_FROM=1000000
          CONNECTION_STRING_SERVICEDIRECTORY='${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}'
          CONNECTION_STRING_REFERRAL='${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}'
          CONNECTION_STRING_REPORT='${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}'
          ENCRYPTION_KEY='${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}'
          INITIALISATION_VECTOR='${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}'
          EXAMPLE_SEED='True'
          EOF

      - name: Get Workflow Runner IP
        id: runner-ip
        uses: ./.github/actions/get-runner-ip-address

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add Azure Firewall Rule
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Add"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: e2e-seed-script

      - name: Run Setup
        shell: bash
        run: npm run setup:dev

      - name: Remove Azure Firewall Rule
        if: always()
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Remove"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: e2e-seed-script

  run-teardown-script:
    needs: [run-setup-script]
    if: ${{ inputs.teardown == 'True' }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: "test/e2e-seed-data-framework"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Jod"

      - name: Install NPM Packages
        shell: bash
        run: npm i

      - name: Initialise Environment Variables
        shell: bash
        run: |
          cat <<EOF>> .env
          IDS_START_FROM=1000000
          CONNECTION_STRING_SERVICEDIRECTORY='${{ secrets.CONNECTION_STRING_SERVICE_DIRECTORY_DATABASE }}'
          CONNECTION_STRING_REFERRAL='${{ secrets.CONNECTION_STRING_REFERRAL_DATABASE }}'
          CONNECTION_STRING_REPORT='${{ secrets.CONNECTION_STRING_REPORT_DATABASE }}'
          ENCRYPTION_KEY='${{ secrets.REFERRAL_COLUMN_ENCRYPTION_KEY }}'
          INITIALISATION_VECTOR='${{ secrets.REFERRAL_COLUMN_INITIALISATION_VECTOR }}'
          EXAMPLE_SEED='True'
          EOF

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Workflow Runner IP
        id: runner-ip
        uses: ./.github/actions/get-runner-ip-address

      - name: Add Azure Firewall Rule
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Add"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: e2e-seed-script

      - name: Run Teardown
        shell: bash
        run: npm run teardown:dev

      - name: Remove Azure Firewall Rule
        if: always()
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Remove"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: e2e-seed-script
