name: Run SQL Script
run-name: Run SQL Script for the ${{ inputs.display_name }} database

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Environment to apply database SQL script to
      display_name:
        required: true
        type: string
        description: The database being updated  
      keyvault_secret_name:
        required: true
        type: string
        description: Name of the secret containing the database connection string
      sql_file_path:
        required: true
        type: string
        description: Path to the SQL file

jobs:
  run-script-against-database:
    if: startsWith(inputs.environment, 'Test')
    name: Runs the SQL script against the ${{ inputs.display_name }}
    runs-on: windows-2022
    environment: ${{ inputs.environment }}
    env:
      KEYVAULT_NAME: ${{ vars.AZURE_RESOURCE_PREFIX }}-kv-fh-general
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
      SQL_SERVER: ${{ vars.AZURE_RESOURCE_PREFIX }}-as-fh-sql-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Workflow Runner IP
        id: runner-ip
        uses: ./.github/actions/get-runner-ip-address

      - name: Add Azure Firewall Rule
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Add"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: sql-script-rule
          
      - name: Run SQL Script PowerShell
        uses: ./.github/actions/run-sql-script
        with:
          keyvault_name: ${{ env.KEYVAULT_NAME }}
          keyvault_secret_name: ${{ inputs.keyvault_secret_name }}
          sql_file_path: ${{ inputs.sql_file_path }}
        
      - name: Remove Azure Firewall Rule
        if: always()
        uses: ./.github/actions/azure-firewall-ip
        with:
          ip_address: ${{ steps.runner-ip.outputs.ip_address }}
          action: "Remove"
          az_resource_group: ${{ env.RESOURCE_GROUP }}
          az_sql_server_name: ${{ env.SQL_SERVER }}
          az_firewall_rule_name: sql-script-rule    