name: Deploy Function

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      project_name:
        required: true
        type: string
      keyvault_prefix:
        required: true
        type: string
      app_name:
        required: true
        type: string
      test_project_name:
        required: true
        type: string
      project_type:
        required: true
        type: string

jobs:
  run-acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    env:
      KEYVAULT: ${{ vars.AZURE_RESOURCE_PREFIX }}-kv-fh-admin
      RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_PREFIX }}-familyhubs
      API_APP_NAME: ${{ vars.AZURE_RESOURCE_PREFIX }}-${{ inputs.app_name }}
      APP_FIREWALL_NAME: acceptance-tests
      PROJECT_PATH: ${{ github.workspace }}/src/${{ inputs.project_type }}/${{ inputs.project_name }}/acceptance-tests/${{ inputs.test_project_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ vars.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get Workflow Runner IP
        id: runner-ip
        uses: ./.github/actions/get-runner-ip-address

      - name: Add IP Address to App Firewall
        shell: pwsh
        run: |-
          az webapp config access-restriction add -g ${{ env.RESOURCE_GROUP }} -n ${{ env.API_APP_NAME }} --rule-name ${{ env.APP_FIREWALL_NAME }} --action Allow --ip-address ${{ steps.runner-ip.outputs.ip_address }} --priority 50

      - name: Run Acceptance Tests
        shell: pwsh
        run: |-
          dotnet user-secrets set "AppConfiguration:KeyVaultIdentifier" "${{ env.KEYVAULT }}" --project ${{ env.PROJECT_PATH }}
          dotnet user-secrets set "AppConfiguration:KeyVaultPrefix" "${{ inputs.keyvault_prefix }}" --project ${{ env.PROJECT_PATH }}
          dotnet test "${{ env.PROJECT_PATH }}/${{ inputs.test_project_name }}.csproj" --logger "html;logfilename=testResults.html"
        
      - name: Remove IP Address from App Firewall
        if: always()
        shell: pwsh
        run: |-
          az webapp config access-restriction remove -g ${{ env.RESOURCE_GROUP }} -n ${{ env.API_APP_NAME }} --rule-name ${{ env.APP_FIREWALL_NAME }}  