name: Run Playwright E2E Tests

on:
  workflow_call:
    inputs:
      environment:
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for running E2E tests
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Test'
          - 'Test2'
          - 'Pre-production'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  SEED_SCRIPT_WORKING_DIRECTORY: "test/e2e-seed-data-framework"

jobs:
  pre-test-teardown:
    if: ${{ inputs.environment != 'Production' }} # TODO: Guard clause can be moved to deploy.yml
    name: Pre-Test Database Teardown
    uses: ./.github/workflows/e2e-seed-database.yml
    with:
      environment: ${{ inputs.environment }}
      action: 'Teardown'
    secrets: inherit
  
  pre-test-setup:
    needs: [ pre-test-teardown ]
    name: Pre-Test Database Setup
    uses: ./.github/workflows/e2e-seed-database.yml
    with:
      environment: ${{ inputs.environment }}
      action: 'Setup'
    secrets: inherit
  
  run-test-suites:
    needs: [ pre-test-setup ]
    name: Run ${{ matrix.job_name }}
    strategy:
      fail-fast: false
      matrix:
        suite: [ find-e2e-tests, manage-e2e-tests ]
        include:
          - suite: find-e2e-tests
            job_name: "Find E2E Test Suite"
          - suite: manage-e2e-tests
            job_name: "Manage E2E Test Suite"
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Pass Test
        if: ${{ matrix.suite == 'find-e2e-tests' }}
        shell: bash
        run: exit 0
        
      - name: Pass Test
        if: ${{ matrix.suite == 'manage-e2e-tests' }}
        shell: bash
        run: exit 0
  
  post-test-teardown:
    needs: [ run-test-suites ]
    name: Post-Test Database Teardown
    uses: ./.github/workflows/e2e-seed-database.yml
    with:
      environment: ${{ inputs.environment }}
      action: 'Teardown'
    secrets: inherit